# Generated by Django 5.0.4 on 2024-06-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('modelo', models.PositiveBigIntegerField()),
                ('marca', models.CharField(max_length=30)),
                ('Referencia', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Valor', models.PositiveIntegerField()),
            ],
        ),
    ]
